sonar.projectKey=Tomvelcas_RetoRappiAI
sonar.organization=tomvelcas

sonar.sourceEncoding=UTF-8

sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests,frontend/src/lib/__tests__
sonar.test.inclusions=backend/tests/**/*.py,frontend/src/lib/__tests__/**/*.test.ts

sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/dist/**,**/*.d.ts
sonar.coverage.exclusions=backend/tests/**,frontend/src/**/*.test.ts

sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
